### ISSUE TITLE
Support Java 9 and 10 for RefApp

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/refapp#3]
Dependent issue: cuba-platform/cuba#910

**Comment by andreysubbotin** [comment]
RefApp commit:
https://git.haulmont.com/platform/refapp/commit/253d29c619850f2c5331ae37c6c0b1bceee10f86

**Comment by andreysubbotin** [comment]
https://git.haulmont.com/platform/refapp/commit/61cad6df0eb1cca94f391411dc6e2524b5d0f41b

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[b2e6c18a](https://git.haulmont.com/platform/refapp/commit/b2e6c18a715ddedffb767e013dd60eade616d634) in **master** - Support Java 9 and 10 for RefApp #3

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[2720966f](https://git.haulmont.com/platform/refapp/commit/2720966fdf1a915ec628e0878b7750ad7d30dac9) in **master** - Support Java 9 and 10 for RefApp #3
