### ISSUE TITLE
Work load generator

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/refapp#7]
Provide JMX bean that will generate random data for entities:

- users
- colors
- cars
- drivers
- plants
- repairs
- call signs
- pricing regions

We should specify number of generated records  with parameter.

It is required for testing of UI components and performance testing of system.

Please use names / titles similar to real world data

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[654d5271](https://git.haulmont.com/platform/refapp/commit/654d52717627762d5fecdcef7045de641d929b5c) in **release_6_10** - Work load generator #7

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[c04bc0f7](https://git.haulmont.com/platform/refapp/commit/c04bc0f731cb895a33886e79a2dd3cf1c9a2426f) in **master** - Work load generator #7

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[fba60673](https://git.haulmont.com/platform/refapp/commit/fba60673fbd5568e44eb1a104b99650dfe408746) in **release_6_10** - Work load generator #7

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[31dc00f4](https://git.haulmont.com/platform/refapp/commit/31dc00f44705828853555208502082391fe5d1f0) in **master** - Work load generator #7

**Comment by sofronovsd** [comment]
Now it is possible to create some random entities via JMX bean `WorkLoadGenerator`. 

You could find it in JMX console: 

![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/3e590f1e-3ff0-441f-8b12-b304d5f4b952)

To generate some entities you need to enter a count as a parameter and press the invoke button:

![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/02f1b490-c412-4b4f-ac2f-a7474bf255df)
![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/27d1d0a2-5b69-44e6-8bb0-f6e7742638c2)

Pay attention that some entities will only be generated if other related entities were created.

**Comment by natfirst** [comment]
"Pay attention that some entities will only be generated if other related entities were created." In this case, the system should return the text notification in the result screen, not the java.lang.IllegalStateException with stacktrace.

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[1002503d](https://git.haulmont.com/platform/refapp/commit/1002503d68f82859d9db5cbe0351c8ba73b46bca) in **release_6_10** - Work load generator #7

**Comment by haulmont-git** [comment]
Git changesets by `sofronov`: 

[8b81090e](https://git.haulmont.com/platform/refapp/commit/8b81090e27c58641e30ae1e369151fcaaecd2eed) in **master** - Work load generator #7

**Comment by sofronovsd** [comment]
Changed the output of error messages on the resulting window.
